[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./builds/uniswap/"},
    { access = "read", path = "./test/the-rewarder/dvt-distribution.json"},
    { access = "read", path = "./test/the-rewarder/weth-distribution.json"},
    { access = "read", path = "./test/withdrawal/withdrawals.json"}
]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", "solmate/=lib/solmate/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
